### ISSUE TITLE
Формы

### ISSUE THREAD

**Issue by supercute** [iv-tsim/autofieldNew#1]
https://github.com/iv-tsim/autofieldNew/blob/18a32d4a7eed7142d2e79aaee255586fe9f0bb44/js/main.js#L39-L42
Переменная data у тебя не обьявлена. Самый простой вариант сериализовать все поля внутри формы и передать в body. Для jquery можно использовать $(form).serialize()

https://github.com/iv-tsim/autofieldNew/blob/18a32d4a7eed7142d2e79aaee255586fe9f0bb44/js/main.js#L79-L82

То же самое.

https://github.com/iv-tsim/autofieldNew/blob/18a32d4a7eed7142d2e79aaee255586fe9f0bb44/js/main.js#L557
Вешать событие на все элементы очень плохое решение, в контексте небольшой задачи можно использовать, но осторожно.

Тут именно тот случай

https://github.com/iv-tsim/autofieldNew/blob/18a32d4a7eed7142d2e79aaee255586fe9f0bb44/js/main.js#L682-L684

Отменяет все события клика для которых !target.closest('.menu.active')  на странице и поэтому кнопки submit форм не срабатывают на клик.

**Comment by iv-tsim** [comment]
Кажется, все поправил
